import os

os.system("cd initial_child_0/ & python ../../simulate_exchanger.py --file initial_child_0_sim.out")
os.system("cd child_0_40/ & python ../../simulate_exchanger.py --file child_0_40_sim.out") 
os.system("cd child_1_17/ & python ../../simulate_exchanger.py --file child_1_17_sim.out") 
os.system("cd child_2_43/ & python ../../simulate_exchanger.py --file child_2_43_sim.out") 
os.system("cd child_5_33/ & python ../../simulate_exchanger.py --file child_5_33_sim.out") 
os.system("cd child_10_47/ & python ../../simulate_exchanger.py --file child_10_47_sim.out") 
os.system("cd child_14_23/ & python ../../simulate_exchanger.py --file child_14_23_sim.out") 
os.system("cd child_16_73/ & python ../../simulate_exchanger.py --file child_16_73_sim.out") 
os.system("cd child_19_60/ & python ../../simulate_exchanger.py --file child_19_60_sim.out") 
os.system("cd child_25_33/ & python ../../simulate_exchanger.py --file child_25_33_sim.out") 
os.system("cd child_29_17/ & python ../../simulate_exchanger.py --file child_29_17_sim.out") 
os.system("cd child_30_48/ & python ../../simulate_exchanger.py --file child_30_48_sim.out") 
os.system("cd child_31_50/ & python ../../simulate_exchanger.py --file child_31_50_sim.out") 
os.system("cd child_44_30/ & python ../../simulate_exchanger.py --file child_44_30_sim.out") 
os.system("cd child_45_53/ & python ../../simulate_exchanger.py --file child_45_53_sim.out") 
os.system("cd child_49_59/ & python ../../simulate_exchanger.py --file child_49_59_sim.out") 
os.system("cd child_52_27/ & python ../../simulate_exchanger.py --file child_52_27_sim.out")  
os.system("cd child_54_12/ & python ../../simulate_exchanger.py --file child_54_12_sim.out")  
os.system("cd child_57_44/ & python ../../simulate_exchanger.py --file child_57_44_sim.out")  
os.system("cd child_64_22/ & python ../../simulate_exchanger.py --file child_64_22_sim.out") 
